In [3]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
# Import dataset
ds=pd.read_csv("Car_Data.csv")
ds

name    company  year          Price  \
0      Hyundai Santro Xing XO eRLX Euro III    Hyundai  2007         80,000   
1                   Mahindra Jeep CL550 MDI   Mahindra  2006       4,25,000   
2                Maruti Suzuki Alto 800 Vxi     Maruti  2018  Ask For Price   
3    Hyundai Grand i10 Magna 1.2 Kappa VTVT    Hyundai  2014       3,25,000   
4          Ford EcoSport Titanium 1.5L TDCi       Ford  2014       5,75,000   
..                                      ...        ...   ...            ...   
887                                      Ta       Tara  zest       3,10,000   
888                     Tata Zest XM Diesel       Tata  2018       2,60,000   
889                      Mahindra Quanto C8   Mahindra  2013       3,90,000   
890                Honda Amaze 1.2 E i VTEC      Honda  2014       1,80,000   
891               Chevrolet Sail 1.2 LT ABS  Chevrolet  2014       1,60,000   

     kms_driven fuel_type  
0    45,000 kms    Petrol  
1        40 kms    Diesel  
2    22,000 kms    Petrol  
3    28,000 kms    Petrol  
4    36,000 kms    Diesel  
..          ...       ...  
887         NaN       NaN  
888  27,000 kms    Diesel  
889  40,000 kms    Diesel  
890      Petrol       NaN  
891      Petrol       NaN  

[892 rows x 6 columns]

In [5]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB


In [6]:
ds.describe()

name company  year          Price  kms_driven fuel_type
count          892     892   892            892         840       837
unique         525      48    61            274         258         3
top     Honda City  Maruti  2015  Ask For Price  45,000 kms    Petrol
freq            13     235   117             35          30       440

In [7]:
ds["year"].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [8]:
ds.dropna(inplace=True)

In [9]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 837 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        837 non-null    object
 1   company     837 non-null    object
 2   year        837 non-null    object
 3   Price       837 non-null    object
 4   kms_driven  837 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 45.8+ KB


In [10]:
# For year
ds["year"]=pd.to_numeric(ds["year"],errors='coerce')

In [11]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 837 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        837 non-null    object
 1   company     837 non-null    object
 2   year        837 non-null    int64 
 3   Price       837 non-null    object
 4   kms_driven  837 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int64(1), object(5)
memory usage: 45.8+ KB


In [12]:
# For Price
ds["Price"].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,5

In [13]:
ds["Price"]=ds["Price"].str.replace(",","")


In [14]:
ds["Price"]=pd.to_numeric(ds["Price"],errors='coerce')

In [15]:
ds["Price"].unique()

array([  80000.,  425000.,      nan,  325000.,  575000.,  175000.,
        190000.,  830000.,  250000.,  182000.,  315000.,  415000.,
        320000., 1000000.,  500000.,  350000.,  160000.,  310000.,
         75000.,  100000.,  290000.,   95000.,  180000.,  385000.,
        105000.,  650000.,  689999.,  448000.,  549000.,  501000.,
        489999.,  280000.,  349999.,  284999.,  345000.,  499999.,
        235000.,  249999., 1475000.,  395000.,  220000.,  170000.,
         85000.,  200000.,  570000.,  110000.,  448999., 1891111.,
        159500.,  344999.,  449999.,  865000.,  699000.,  375000.,
        224999., 1200000.,  195000.,  351000.,  240000.,   90000.,
        155000.,  600000.,  189500.,  210000.,  390000.,  135000.,
       1600000.,  701000.,  265000.,  525000.,  372000.,  635000.,
        550000.,  485000.,  329500.,  251111.,  569999.,   69999.,
        299999.,  399999.,  450000.,  270000.,  158400.,  179000.,
        125000.,  299000.,  150000.,  285000.,  340000.,   700

In [16]:
# for kms_driven
ds["kms_driven"]=ds["kms_driven"].str.replace(",","").str.replace("kms","")

In [17]:
ds["kms_driven"]=pd.to_numeric(ds["kms_driven"],errors='coerce')

In [18]:
ds["kms_driven"].unique()

array([ 45000,     40,  22000,  28000,  36000,  59000,  41000,  25000,
        24530,  60000,  30000,  32000,  48660,   4000,  16934,  43000,
        35550,  39522,  39000,  55000,  72000,  15975,  70000,  23452,
        35522,  48508,  15487,  82000,  20000,  68000,  38000,  27000,
        33000,  46000,  16000,  47000,  35000,  30874,  15000,  29685,
       130000,  19000,  54000,  13000,  38200,  50000,  13500,   3600,
        45863,  60500,  12500,  18000,  13349,  29000,  44000,  42000,
        14000,  49000,  36200,  51000, 104000,  33333,  33600,   5600,
         7500,  24330,  65480,  28028, 200000,  99000,   2800,  21000,
        11000,  66000,   3000,   7000,  38500,  37200,  43200,  24800,
        45872,  40000,  11400,  97200,  52000,  31000, 175430,  37000,
        65000,   3350,  75000,  62000,  73000,   2200,  54870,  34580,
        97000,     60,  80200,   3200,      0,   5000,    588,  71200,
       175400,   9300,  56758,  10000,  56450,  56000,  32700,   9000,
      

In [17]:
ds

name    company    year     Price  \
0      Hyundai Santro Xing XO eRLX Euro III    Hyundai  2007.0   80000.0   
1                   Mahindra Jeep CL550 MDI   Mahindra  2006.0  425000.0   
2                Maruti Suzuki Alto 800 Vxi     Maruti  2018.0       NaN   
3    Hyundai Grand i10 Magna 1.2 Kappa VTVT    Hyundai  2014.0  325000.0   
4          Ford EcoSport Titanium 1.5L TDCi       Ford  2014.0  575000.0   
..                                      ...        ...     ...       ...   
887                                      Ta       Tara     NaN  310000.0   
888                     Tata Zest XM Diesel       Tata  2018.0  260000.0   
889                      Mahindra Quanto C8   Mahindra  2013.0  390000.0   
890                Honda Amaze 1.2 E i VTEC      Honda  2014.0  180000.0   
891               Chevrolet Sail 1.2 LT ABS  Chevrolet  2014.0  160000.0   

     kms_driven fuel_type  
0       45000.0    Petrol  
1          40.0    Diesel  
2       22000.0    Petrol  
3       28000.0    Petrol  
4       36000.0    Diesel  
..          ...       ...  
887         NaN       NaN  
888     27000.0    Diesel  
889     40000.0    Diesel  
890         NaN       NaN  
891         NaN       NaN  

[892 rows x 6 columns]

In [19]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 837 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        837 non-null    object 
 1   company     837 non-null    object 
 2   year        837 non-null    int64  
 3   Price       816 non-null    float64
 4   kms_driven  837 non-null    int64  
 5   fuel_type   837 non-null    object 
dtypes: float64(1), int64(2), object(3)
memory usage: 45.8+ KB


In [20]:
# Handling outliers
ds=ds[ds["kms_driven"]>=10000]

In [21]:
ds=ds[ds["kms_driven"]<=200000]

In [22]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 751 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        751 non-null    object 
 1   company     751 non-null    object 
 2   year        751 non-null    int64  
 3   Price       736 non-null    float64
 4   kms_driven  751 non-null    int64  
 5   fuel_type   751 non-null    object 
dtypes: float64(1), int64(2), object(3)
memory usage: 41.1+ KB


In [23]:
ds["kms_driven"].unique()

array([ 45000,  22000,  28000,  36000,  59000,  41000,  25000,  24530,
        60000,  30000,  32000,  48660,  16934,  43000,  35550,  39522,
        39000,  55000,  72000,  15975,  70000,  23452,  35522,  48508,
        15487,  82000,  20000,  68000,  38000,  27000,  33000,  46000,
        16000,  47000,  35000,  30874,  15000,  29685, 130000,  19000,
        54000,  13000,  38200,  50000,  13500,  45863,  60500,  12500,
        18000,  13349,  29000,  44000,  42000,  14000,  49000,  36200,
        51000, 104000,  33333,  33600,  24330,  65480,  28028, 200000,
        99000,  21000,  11000,  66000,  38500,  37200,  43200,  24800,
        45872,  40000,  11400,  97200,  52000,  31000, 175430,  37000,
        65000,  75000,  62000,  73000,  54870,  34580,  97000,  80200,
        71200, 175400,  56758,  10000,  56450,  56000,  32700, 160000,
        84000,  58559,  57000, 170000,  80000,  23000,  34000,  48000,
        90000,  12000,  69900, 166000,  24000,  36469,  24695,  15141,
      

In [24]:
sorted(ds["kms_driven"].unique())# To find minimun and maximum value

[np.int64(10000),
 np.int64(10544),
 np.int64(10750),
 np.int64(11000),
 np.int64(11400),
 np.int64(11500),
 np.int64(11523),
 np.int64(12000),
 np.int64(12500),
 np.int64(12516),
 np.int64(13000),
 np.int64(13349),
 np.int64(13500),
 np.int64(13900),
 np.int64(14000),
 np.int64(15000),
 np.int64(15141),
 np.int64(15487),
 np.int64(15574),
 np.int64(15975),
 np.int64(16000),
 np.int64(16934),
 np.int64(18000),
 np.int64(18500),
 np.int64(19000),
 np.int64(19336),
 np.int64(20000),
 np.int64(21000),
 np.int64(22000),
 np.int64(22134),
 np.int64(23000),
 np.int64(23452),
 np.int64(24000),
 np.int64(24330),
 np.int64(24530),
 np.int64(24652),
 np.int64(24695),
 np.int64(24800),
 np.int64(25000),
 np.int64(25500),
 np.int64(26500),
 np.int64(27000),
 np.int64(28000),
 np.int64(28028),
 np.int64(28400),
 np.int64(28600),
 np.int64(29000),
 np.int64(29500),
 np.int64(29685),
 np.int64(30000),
 np.int64(30201),
 np.int64(30600),
 np.int64(30874),
 np.int64(31000),
 np.int64(32000),
 np.int64(

In [25]:
ds["fuel_type"].unique() # not nan(empty values)

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [26]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 751 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        751 non-null    object 
 1   company     751 non-null    object 
 2   year        751 non-null    int64  
 3   Price       736 non-null    float64
 4   kms_driven  751 non-null    int64  
 5   fuel_type   751 non-null    object 
dtypes: float64(1), int64(2), object(3)
memory usage: 41.1+ KB


In [27]:
ds["company"].unique()

array(['Hyundai', 'Maruti', 'Ford', 'Skoda', 'Mahindra', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat',
       'Mercedes', 'Land', 'Force', 'Jaguar', 'Volvo'], dtype=object)

In [28]:
# To remove company names in name column that repeated in name column
for i in ds.index:
    company=ds.loc[i,"company"]
    name=ds.loc[i,"name"]
    name=name.replace(company,"").strip()
    ds.loc[i,"name"]=name


In [29]:
ds["name"].unique()

array(['Santro Xing XO eRLX Euro III', 'Suzuki Alto 800 Vxi',
       'Grand i10 Magna 1.2 Kappa VTVT', 'EcoSport Titanium 1.5L TDCi',
       'Figo', 'Eon', 'EcoSport Ambiente 1.5L TDCi',
       'Suzuki Alto K10 VXi AMT', 'Fabia Classic 1.2 MPI',
       'Suzuki Stingray VXi', 'Elite i20 Magna 1.2', 'Scorpio SLE BS IV',
       'Q7', 'Scorpio S10', 'Suzuki Alto 800', 'i20 Sportz 1.2',
       'Suzuki Alto 800 Lx', 'Suzuki Vitara Brezza ZDi', 'Suzuki Alto LX',
       'Bolero DI', 'Suzuki Swift Dzire ZDi', 'Scorpio S10 4WD',
       'Suzuki Swift Vdi BSIII', 'Suzuki Wagon R VXi BS III',
       'Suzuki Wagon R VXi Minor', 'Innova 2.0 G 8 STR BS IV',
       'Lodgy 85 PS RXL', 'Yeti Ambition 2.0 TDI CR 4x2',
       'Suzuki Baleno Delta 1.2', 'Duster 110 PS RxZ Diesel Plus',
       'Duster 85 PS RxE Diesel', 'City 1.5 S MT', 'Suzuki Dzire',
       'Amaze', 'Amaze 1.5 SX i DTEC', 'City', 'Redi GO S',
       'Suzuki SX4 ZXI MT', 'Pajero Sport Limited Edition',
       'Suzuki Swift VXi 1.2 ABS BS IV

In [30]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 751 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        751 non-null    object 
 1   company     751 non-null    object 
 2   year        751 non-null    int64  
 3   Price       736 non-null    float64
 4   kms_driven  751 non-null    int64  
 5   fuel_type   751 non-null    object 
dtypes: float64(1), int64(2), object(3)
memory usage: 57.2+ KB


In [31]:
sorted(ds["year"].unique())

[np.int64(1995),
 np.int64(2000),
 np.int64(2001),
 np.int64(2002),
 np.int64(2003),
 np.int64(2004),
 np.int64(2005),
 np.int64(2006),
 np.int64(2007),
 np.int64(2008),
 np.int64(2009),
 np.int64(2010),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018)]

In [32]:
sorted(ds["Price"].unique())

[np.float64(30000.0),
 np.float64(55000.0),
 np.float64(80000.0),
 np.float64(nan),
 np.float64(32000.0),
 np.float64(35000.0),
 np.float64(35999.0),
 np.float64(39999.0),
 np.float64(40000.0),
 np.float64(42000.0),
 np.float64(45000.0),
 np.float64(48000.0),
 np.float64(50500.0),
 np.float64(51999.0),
 np.float64(53000.0),
 np.float64(57000.0),
 np.float64(59000.0),
 np.float64(60000.0),
 np.float64(65000.0),
 np.float64(68000.0),
 np.float64(69999.0),
 np.float64(70000.0),
 np.float64(71000.0),
 np.float64(72500.0),
 np.float64(75000.0),
 np.float64(85000.0),
 np.float64(88000.0),
 np.float64(90000.0),
 np.float64(90001.0),
 np.float64(95000.0),
 np.float64(98500.0),
 np.float64(99000.0),
 np.float64(99999.0),
 np.float64(100000.0),
 np.float64(105000.0),
 np.float64(110000.0),
 np.float64(114990.0),
 np.float64(115000.0),
 np.float64(120000.0),
 np.float64(123000.0),
 np.float64(125000.0),
 np.float64(130000.0),
 np.float64(135000.0),
 np.float64(140000.0),
 np.float64(145000.0),
 n

In [33]:
ds.duplicated().unique()

array([False,  True])

In [34]:
ds.duplicated().sum()

np.int64(85)

In [35]:
ds.drop_duplicates(inplace=True)

In [36]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 666 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        666 non-null    object 
 1   company     666 non-null    object 
 2   year        666 non-null    int64  
 3   Price       651 non-null    float64
 4   kms_driven  666 non-null    int64  
 5   fuel_type   666 non-null    object 
dtypes: float64(1), int64(2), object(3)
memory usage: 36.4+ KB


In [37]:
# To remove null values(Empty cells)
ds["Price"].isnull().sum()

np.int64(15)

In [38]:
ds=ds.dropna(subset=["Price"])

In [39]:
ds["Price"].isnull().sum()

np.int64(0)

In [40]:
ds

name   company  year     Price  kms_driven  \
0      Santro Xing XO eRLX Euro III   Hyundai  2007   80000.0       45000   
3    Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014  325000.0       28000   
4       EcoSport Titanium 1.5L TDCi      Ford  2014  575000.0       36000   
6                              Figo      Ford  2012  175000.0       41000   
7                               Eon   Hyundai  2013  190000.0       25000   
..                              ...       ...   ...       ...         ...   
883             Suzuki Ritz VXI ABS    Maruti  2011  270000.0       50000   
885            Indica V2 DLE BS III      Tata  2009  110000.0       30000   
886                   Corolla Altis    Toyota  2009  300000.0      132000   
888                  Zest XM Diesel      Tata  2018  260000.0       27000   
889                       Quanto C8  Mahindra  2013  390000.0       40000   

    fuel_type  
0      Petrol  
3      Petrol  
4      Diesel  
6      Diesel  
7      Petrol  
..        ...  
883    Petrol  
885    Diesel  
886    Petrol  
888    Diesel  
889    Diesel  

[651 rows x 6 columns]

In [41]:
print(ds.to_string())

                                         name     company  year      Price  kms_driven fuel_type
0                Santro Xing XO eRLX Euro III     Hyundai  2007    80000.0       45000    Petrol
3              Grand i10 Magna 1.2 Kappa VTVT     Hyundai  2014   325000.0       28000    Petrol
4                 EcoSport Titanium 1.5L TDCi        Ford  2014   575000.0       36000    Diesel
6                                        Figo        Ford  2012   175000.0       41000    Diesel
7                                         Eon     Hyundai  2013   190000.0       25000    Petrol
8                 EcoSport Ambiente 1.5L TDCi        Ford  2016   830000.0       24530    Diesel
9                     Suzuki Alto K10 VXi AMT      Maruti  2015   250000.0       60000    Petrol
10                      Fabia Classic 1.2 MPI       Skoda  2010   182000.0       60000    Petrol
11                        Suzuki Stingray VXi      Maruti  2015   315000.0       30000    Petrol
12                        Elit

In [ ]:
df.to_csv("New_Cleaned_Data.csv")